ALTER TABLE `stockdataset`.`tb_stock_list`
ADD COLUMN `TYPE` VARCHAR(50) NULL AFTER `SHARE_IN_MARKET`,
ADD COLUMN `REGION` VARCHAR(50) NULL AFTER `TYPE`,
ADD COLUMN `SHORT_NAME` VARCHAR(100) NULL AFTER `REGION`,
ADD COLUMN `FULL_NAME` VARCHAR(50) NULL AFTER `SHORT_NAME`,
ADD COLUMN `ENGLISH_NAME` VARCHAR(50) NULL AFTER `FULL_NAME`,
ADD COLUMN `EMAIL` VARCHAR(50) NULL AFTER `ENGLISH_NAME`,
ADD COLUMN `TELEPHONE` VARCHAR(50) NULL AFTER `EMAIL`,
ADD COLUMN `CAPITAL` VARCHAR(50) NULL AFTER `TELEPHONE`,
ADD COLUMN `CHAIRMAN` VARCHAR(50) NULL AFTER `CAPITAL`,
ADD COLUMN `MAIN_BUSINESS` VARCHAR(500) NULL AFTER `CHAIRMAN`;
