CREATE TABLE `tb_stock_financial_zycwzb` (
  `CODE` varchar(10) NOT NULL,
  `DATE` date NOT NULL,
  `JBMGSY_Y` double DEFAULT NULL COMMENT '基本每股收益(元)',
  `MGJZC_Y` double DEFAULT NULL COMMENT '每股净资产(元)',
  `MGJYHDCSDXJLLJE_Y` double DEFAULT NULL COMMENT '每股经营活动产生的现金流量净额(元)',
  `ZYYWSR_WY` double DEFAULT NULL COMMENT '主营业务收入(万元)',
  `ZYYWLR_WY` double DEFAULT NULL COMMENT '主营业务利润(万元)',
  `YYLR_WY` double DEFAULT NULL COMMENT '营业利润(万元)',
  `TZSY_WY` double DEFAULT NULL COMMENT '投资收益(万元)',
  `YYWSZJE_WY` double DEFAULT NULL COMMENT '营业外收支净额(万元)',
  `LRZE_WY` double DEFAULT NULL COMMENT '利润总额(万元)',
  `JLR_WY` double DEFAULT NULL COMMENT '净利润(万元)',
  `JLR_KCFJCXSYH_WY` double DEFAULT NULL COMMENT '净利润(扣除非经常性损益后)(万元)',
  `JYHDCSDXJLLJE_WY` double DEFAULT NULL COMMENT '经营活动产生的现金流量净额(万元)',
  `XJJXJDJWJZJE_WY` double DEFAULT NULL COMMENT '现金及现金等价物净增加额(万元)',
  `ZZC_WY` double DEFAULT NULL COMMENT '总资产(万元)',
  `LDZC_WY` double DEFAULT NULL COMMENT '流动资产(万元)',
  `ZFZ_WY` double DEFAULT NULL COMMENT '总负债(万元)',
  `LDFZ_WY` double DEFAULT NULL COMMENT '流动负债(万元)',
  `GDQY_WY` double DEFAULT NULL COMMENT '股东权益不含少数股东权益(万元)',
  `JZCSYLJQ` double DEFAULT NULL COMMENT '净资产收益率加权',
  `PERIOD_TYPE` varchar(10) NOT NULL,
  PRIMARY KEY (`CODE`,`DATE`,`PERIOD_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tb_stock_financial_lrb` (
  `CODE` varchar(10) NOT NULL,
  `DATE` date NOT NULL,
  `YYZSR_WY` double DEFAULT NULL COMMENT '营业总收入(万元)',
  `YYSR_WY` double DEFAULT NULL COMMENT '营业收入(万元)',
  `LXSR_WY` double DEFAULT NULL COMMENT '利息收入(万元)',
  `YZBF_WY` double DEFAULT NULL COMMENT '已赚保费(万元)',
  `SXFJYJSR_WY` double DEFAULT NULL COMMENT '手续费及佣金收入(万元)',
  `FDCXXSR_WY` double DEFAULT NULL COMMENT '房地产销售收入(万元)',
  `QTYESR_WY` double DEFAULT NULL COMMENT '其他业务收入(万元)',
  `YYZCB_WY` double DEFAULT NULL COMMENT '营业总成本(万元)',
  `YYCB_WY` double DEFAULT NULL COMMENT '营业成本(万元)',
  `LXZC_WY` double DEFAULT NULL COMMENT '利息支出(万元)',
  `SXFJYJZC_WY` double DEFAULT NULL COMMENT '手续费及佣金支出(万元)',
  `FDCXXCB_WY` double DEFAULT NULL COMMENT '房地产销售成本(万元)',
  `YFFY_WY` double DEFAULT NULL COMMENT '研发费用(万元)',
  `TBJ_WY` double DEFAULT NULL COMMENT '退保金(万元)',
  `PFZCJE_WY` double DEFAULT NULL COMMENT '赔付支出净额(万元)',
  `TQBXHTZBJJE_WY` double DEFAULT NULL COMMENT '提取保险合同准备金净额(万元)',
  `BDHLZC_WY` double DEFAULT NULL COMMENT '保单红利支出(万元)',
  `FBFY_WY` double DEFAULT NULL COMMENT '分保费用(万元)',
  `QTCBFY_WY` double DEFAULT NULL COMMENT '其他业务成本(万元)',
  `YYSJJFJ_WY` double DEFAULT NULL COMMENT '营业税金及附加(万元)',
  `XSFY_WY` double DEFAULT NULL COMMENT '销售费用(万元)',
  `GLFY_WY` double DEFAULT NULL COMMENT '管理费用(万元)',
  `CWFY_WY` double DEFAULT NULL COMMENT '财务费用(万元)',
  `ZCJZSS_WY` double DEFAULT NULL COMMENT '资产减值损失(万元)',
  `GYJJBDSY_WY` double DEFAULT NULL COMMENT '公允价值变动收益(万元)',
  `TZSY_WY` double DEFAULT NULL COMMENT '投资收益(万元)',
  `DLYQYHHYQYDTZSY_WY` double DEFAULT NULL COMMENT '对联营企业和合营企业的投资收益(万元)',
  `HDSY_WY` double DEFAULT NULL COMMENT '汇兑收益(万元)',
  `QHSY_WY` double DEFAULT NULL COMMENT '期货损益(万元)',
  `TGSY_WY` double DEFAULT NULL COMMENT '托管收益(万元)',
  `BTSR_WY` double DEFAULT NULL COMMENT '补贴收入(万元)',
  `QTYWLR_WY` double DEFAULT NULL COMMENT '其他业务利润(万元)',
  `YYLR_WY` double DEFAULT NULL COMMENT '营业利润(万元)',
  `YYWSR_WY` double DEFAULT NULL COMMENT '营业外收入(万元)',
  `YYWZC_WY` double DEFAULT NULL COMMENT '营业外支出(万元)',
  `FLDZCCZSS_WY` double DEFAULT NULL COMMENT '非流动资产处置损失(万元)',
  `LRZE_WY` double DEFAULT NULL COMMENT '利润总额(万元)',
  `SDSFY_WY` double DEFAULT NULL COMMENT '所得税费用(万元)',
  `WQRRZSS_WY` double DEFAULT NULL COMMENT '未确认投资损失(万元)',
  `JLR_WY` double DEFAULT NULL COMMENT '净利润(万元)',
  `GSYMGSSYZDJLR_WY` double DEFAULT NULL COMMENT '归属于母公司所有者的净利润(万元)',
  `BHBFZHBQSXJLR_WY` double DEFAULT NULL COMMENT '被合并方在合并前实现净利润(万元)',
  `SSGDSY_WY` double DEFAULT NULL COMMENT '少数股东损益(万元)',
  `JBMGSY` double DEFAULT NULL COMMENT '基本每股收益',
  `XSMGSY` double DEFAULT NULL COMMENT '稀释每股收益',
  `PERIOD_TYPE` varchar(10) NOT NULL,
  PRIMARY KEY (`CODE`,`DATE`,`PERIOD_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `tb_stock_financial_xjllb` (
  `CODE` varchar(10) NOT NULL,
  `DATE` date NOT NULL,
  `XSSP_TGLWSDDXJ_WY` double DEFAULT NULL COMMENT ' 销售商品、提供劳务收到的现金(万元)',
  `KHCKHTYCFKXJZJE_WY` double DEFAULT NULL COMMENT ' 客户存款和同业存放款项净增加额(万元)',
  `XZYYHJKJZJE_WY` double DEFAULT NULL COMMENT ' 向中央银行借款净增加额(万元',
  `XQTJRJGCRZJJZJE_WY` double DEFAULT NULL COMMENT ' 向其他金融机构拆入资金净增加额(万元)',
  `SDYBXHTBFQDDXJ_WY` double DEFAULT NULL COMMENT ' 收到原保险合同保费取得的现金(万元)',
  `SDZBXYWXJJE_WY` double DEFAULT NULL COMMENT ' 收到再保险业务现金净额(万元)',
  `BHCJJTZJJZJE_WY` double DEFAULT NULL COMMENT ' 保户储金及投资款净增加额(万元)',
  `CZJJXJRZCJZJE_WY` double DEFAULT NULL COMMENT ' 处置交易性金融资产净增加额(万元)',
  `SQLX_SXFJYJDXJ_WY` double DEFAULT NULL COMMENT ' 收取利息、手续费及佣金的现金(万元)',
  `CRZJJZJE_WY` double DEFAULT NULL COMMENT ' 拆入资金净增加额(万元)',
  `HGYWZJJEJE_WY` double DEFAULT NULL COMMENT ' 回购业务资金净增加额(万元)',
  `SDDSFFH_WY` double DEFAULT NULL COMMENT ' 收到的税费返还(万元)',
  `SDDQTYJYHDYGDXJ_WY` double DEFAULT NULL COMMENT ' 收到的其他与经营活动有关的现金(万元)',
  `JYHDXJLRXJ_WY` double DEFAULT NULL COMMENT ' 经营活动现金流入小计(万元)',
  `GMSP_JSLWZFDXJ_WY` double DEFAULT NULL COMMENT ' 购买商品、接受劳务支付的现金(万元)',
  `KHDKJDKJZJE_WY` double DEFAULT NULL COMMENT ' 客户贷款及垫款净增加额(万元)',
  `CFZYYHHTYKXJZJE_WY` double DEFAULT NULL COMMENT ' 存放中央银行和同业款项净增加额(万元)',
  `ZFYBXHTPFKXDXJ_WY` double DEFAULT NULL COMMENT ' 支付原保险合同赔付款项的现金(万元)',
  `ZFLX_SXFJYJDXJ_WY` double DEFAULT NULL COMMENT ' 支付利息、手续费及佣金的现金(万元)',
  `ZFBDHLDXJ_WY` double DEFAULT NULL COMMENT ' 支付保单红利的现金(万元)',
  `ZFGZGYJWZGZFDXJ_WY` double DEFAULT NULL COMMENT ' 支付给职工以及为职工支付的现金(万元)',
  `ZFDGXSF_WY` double DEFAULT NULL COMMENT ' 支付的各项税费(万元)',
  `ZFDQTYJYHDYGDXJ_WY` double DEFAULT NULL COMMENT ' 支付的其他与经营活动有关的现金(万元)',
  `JYHDXJLCXJ_WY` double DEFAULT NULL COMMENT ' 经营活动现金流出小计(万元)',
  `JYHDCSDXJLLJE_WY` double DEFAULT NULL COMMENT ' 经营活动产生的现金流量净额(万元)',
  `HSTZSSDDXJ_WY` double DEFAULT NULL COMMENT ' 收回投资所收到的现金(万元)',
  `QDTZSYSSDDXJ_WY` double DEFAULT NULL COMMENT ' 取得投资收益所收到的现金(万元)',
  `CZGDZC_WXZCHQTCQZCSHSDXJJE_WY` double DEFAULT NULL COMMENT ' 处置固定资产、无形资产和其他长期资产所收回的现金净额(万元)',
  `CZZGSJQTYYDWSDDXJJE_WY` double DEFAULT NULL COMMENT ' 处置子公司及其他营业单位收到的现金净额(万元)',
  `SDDQTYTZHDYGDXJ_WY` double DEFAULT NULL COMMENT ' 收到的其他与投资活动有关的现金(万元)',
  `JSZYHDQCKSSDDXJ_WY` double DEFAULT NULL COMMENT ' 减少质押和定期存款所收到的现金(万元)',
  `TZHDXJLRXJ_WY` double DEFAULT NULL COMMENT ' 投资活动现金流入小计(万元)',
  `GJGDZX_WXZJHQTCQZCSZFDXJ_WY` double DEFAULT NULL COMMENT ' 购建固定资产、无形资产和其他长期资产所支付的现金(万元)',
  `TZSZFDXJ_WY` double DEFAULT NULL COMMENT ' 投资所支付的现金(万元)',
  `ZYDKJZJE_WY` double DEFAULT NULL COMMENT ' 质押贷款净增加额(万元)',
  `QDZGSJQTYYDWZFDXJJE_WY` double DEFAULT NULL COMMENT ' 取得子公司及其他营业单位支付的现金净额(万元)',
  `ZFDQTYTZHDYGDXJ_WY` double DEFAULT NULL COMMENT ' 支付的其他与投资活动有关的现金(万元)',
  `ZJZYHDQCKSZFDXJ_WY` double DEFAULT NULL COMMENT ' 增加质押和定期存款所支付的现金(万元)',
  `TZHDXJLCXJ_WY` double DEFAULT NULL COMMENT ' 投资活动现金流出小计(万元)',
  `TZHDCSDXJLLJE_WY` double DEFAULT NULL COMMENT ' 投资活动产生的现金流量净额(万元)',
  `XSTZSDDXJ_WY` double DEFAULT NULL COMMENT ' 吸收投资收到的现金(万元)',
  `ZGSXSXSGDTZSDDXJ_WY` double DEFAULT NULL COMMENT ' 其中：子公司吸收少数股东投资收到的现金(万元)',
  `QDJKSDDXJ_WY` double DEFAULT NULL COMMENT ' 取得借款收到的现金(万元)',
  `FXZQSDDXJ_WY` double DEFAULT NULL COMMENT ' 发行债券收到的现金(万元)',
  `SDQTYCZHDYGDXJ_WY` double DEFAULT NULL COMMENT ' 收到其他与筹资活动有关的现金(万元)',
  `CZHDXJLRXJ_WY` double DEFAULT NULL COMMENT ' 筹资活动现金流入小计(万元)',
  `CHZWZFDXJ_WY` double DEFAULT NULL COMMENT ' 偿还债务支付的现金(万元)',
  `FPGL_LRHCFLXSZFDXJ_WY` double DEFAULT NULL COMMENT ' 分配股利、利润或偿付利息所支付的现金(万元)',
  `ZGSZFSSGDDGL_LR_WY` double DEFAULT NULL COMMENT ' 其中：子公司支付给少数股东的股利、利润(万元)',
  `ZFQTYCZHDYGDXJ_WY` double DEFAULT NULL COMMENT ' 支付其他与筹资活动有关的现金(万元)',
  `CZHDXJLCXJ_WY` double DEFAULT NULL COMMENT ' 筹资活动现金流出小计(万元)',
  `CZHDCSDXJLLJE_WY` double DEFAULT NULL COMMENT ' 筹资活动产生的现金流量净额(万元)',
  `HLBDDXJJXJDJWDYX_WY` double DEFAULT NULL COMMENT ' 汇率变动对现金及现金等价物的影响(万元)',
  `XJJXJDJWJZJE_WY` double DEFAULT NULL COMMENT ' 现金及现金等价物净增加额(万元)',
  `QCXJJXJDJWYE_WY` double DEFAULT NULL COMMENT ' 加:期初现金及现金等价物余额(万元)',
  `QMXJJXJDJWYE_WY` double DEFAULT NULL COMMENT ' 期末现金及现金等价物余额(万元)',
  `JLR_WY` double DEFAULT NULL COMMENT ' 净利润(万元)',
  `SSGDQY_WY` double DEFAULT NULL COMMENT ' 少数股东损益(万元)',
  `WQRDTZSS_WY` double DEFAULT NULL COMMENT ' 未确认的投资损失(万元)',
  `ZCJZZB_WY` double DEFAULT NULL COMMENT ' 资产减值准备(万元)',
  `GDZCZJ_YQZCZH_SCXWZZJ_WY` double DEFAULT NULL COMMENT ' 固定资产折旧、油气资产折耗、生产性物资折旧(万元)',
  `WXZCTX_WY` double DEFAULT NULL COMMENT ' 无形资产摊销(万元)',
  `CQDTFYTX_WY` double DEFAULT NULL COMMENT ' 长期待摊费用摊销(万元)',
  `DXFYDJS_WY` double DEFAULT NULL COMMENT ' 待摊费用的减少(万元)',
  `YTFYDZJ_WY` double DEFAULT NULL COMMENT ' 预提费用的增加(万元)',
  `CZGDZC_WXZCHQTCQZCDSS_WY` double DEFAULT NULL COMMENT ' 处置固定资产、无形资产和其他长期资产的损失(万元)',
  `GDZCBFSS_WY` double DEFAULT NULL COMMENT ' 固定资产报废损失(万元)',
  `GYJZBDSS_WY` double DEFAULT NULL COMMENT ' 公允价值变动损失(万元)',
  `DYSYZJ_WY` double DEFAULT NULL COMMENT ' 递延收益增加(减：减少)(万元)',
  `YJFZ_WY` double DEFAULT NULL COMMENT ' 预计负债(万元)',
  `CWFY_WY` double DEFAULT NULL COMMENT ' 财务费用(万元)',
  `TZSS_WY` double DEFAULT NULL COMMENT ' 投资损失(万元)',
  `DYSDSZCJS_WY` double DEFAULT NULL COMMENT ' 递延所得税资产减少(万元)',
  `DYSDSFZZJ_WY` double DEFAULT NULL COMMENT ' 递延所得税负债增加(万元)',
  `CHDJS_WY` double DEFAULT NULL COMMENT ' 存货的减少(万元)',
  `JYXYSXMDJS_WY` double DEFAULT NULL COMMENT ' 经营性应收项目的减少(万元)',
  `JYXYFXMDZJ_WY` double DEFAULT NULL COMMENT ' 经营性应付项目的增加(万元)',
  `YWGSWJSKDJS_WY` double DEFAULT NULL COMMENT ' 已完工尚未结算款的减少(减:增加)(万元)',
  `YJSSWWGKDZJ_WY` double DEFAULT NULL COMMENT ' 已结算尚未完工款的增加(减:减少)(万元)',
  `QT_WY` double DEFAULT NULL COMMENT ' 其他(万元)',
  `JYHDCSXJLLJE_WY` double DEFAULT NULL COMMENT ' 经营活动产生现金流量净额(万元)',
  `ZWZWZB_WY` double DEFAULT NULL COMMENT ' 债务转为资本(万元)',
  `YNNDQDKZHGSZQ_WY` double DEFAULT NULL COMMENT ' 一年内到期的可转换公司债券(万元)',
  `RZZRGDZC_WY` double DEFAULT NULL COMMENT ' 融资租入固定资产(万元)',
  `XJDQMYE_WY` double DEFAULT NULL COMMENT ' 现金的期末余额(万元)',
  `XJDQCYE_WY` double DEFAULT NULL COMMENT ' 现金的期初余额(万元)',
  `XJJDJWDQMYE_WY` double DEFAULT NULL COMMENT ' 现金等价物的期末余额(万元)',
  `XJJDJWDQCYE_WY` double DEFAULT NULL COMMENT ' 现金等价物的期初余额(万元)',
  `XJJXJDJWDJZJE_WY` double DEFAULT NULL COMMENT ' 现金及现金等价物的净增加额(万元)',
  `PERIOD_TYPE` varchar(10) NOT NULL,
  PRIMARY KEY (`CODE`,`DATE`,`PERIOD_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
