app:
  preprocessing:
    input_dir: H:\dataset
    input_file_pattern: full
    output_dir: D:\preprocessing
    output_file_prefix: preprocessing_
    keep_header: True
    preprocess_config: ./config/full_data_preprocessing_config.yaml
    generate_seed: True
    output_seed_file_prefix: seed_
  export:
    from_year: 2010
    to_year: 2020
    dir: D:\Output\dataset
    split_year: False
    keep_header: True
  daily:
    num_process: 5
  weekly:
    sse_file_path: ./files/sse.xls
    szse_file_path: ./files/szse.xlsx