app:
  export:
    from_year: 2010
    to_year: 2020
    dir: D:\Output\dataset
    split_year: False
  daily:
    num_process: 10
  weekly:
    sse_file_path: ../files/sse.xls
    szse_file_path: ../szse.xlsx