rows:
  drop_first: 50
  drop_last: 0
columns:
  - column:
      name: CODE
      dtype: string
      action: keep
  - column:
      name: DATE
      dtype: date
      attr: [feature]
      action: keep
  - column:
      name: TCLOSE
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: HIGH
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: LOW
      dtype: numeric
      attr: feature
      action: normalization
  - column:
      name: TOPEN
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: LCLOSE
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: CHG
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCHG
      dtype: string
      attr: [label, feature]
      action: normalization
  - column:
      name: TURNOVER
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: VOTURNOVER
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: VATURNOVER
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: TCAP
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MCAP
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MA5
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MA10
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MA20
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BBI
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BIAS6
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BIAS12
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BIAS24
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BR
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: AR
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: DMA
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: AMA
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MTM
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MAMTM
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PSY6
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PSY12
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: VR
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: KDJ_K
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: KDJ_D
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: KDJ_J
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MACD_DIF
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MACD_DEA
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MACD
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BOLL_UPPER
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BOLL_MIDDLE
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: BOLL_LOWER
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: CCI
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: ROC
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MAROC
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: RSI6
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: RSI12
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: RSI24
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: WR6
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: WR14
      dtype: numeric
      attr: [feature]
      action: normalization