rows:
  drop_first: 50
  drop_last: 0
columns:
  - column:
      name: PCHG
      dtype: numeric
      attr: [ label ]
      action: none
  - column:
      name: PCA1
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA2
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA3
      dtype: numeric
      attr: feature
      action: normalization
  - column:
      name: PCA4
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA5
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA6
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA7
      dtype: string
      attr: [feature]
      action: normalization
  - column:
      name: PCA8
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA9
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA10
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA11
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA12
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA13
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA14
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA15
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA16
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA17
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA18
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA19
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCA20
      dtype: numeric
      attr: [feature]
      action: normalization