rows:
  drop_first: 50
  drop_last: 0
columns:
  - column:
      name: CODE
      dtype: string
      action: drop
  - column:
      name: DATE
      dtype: date
      attr: [feature]
      action: normalization
  - column:
      name: TCLOSE
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: HIGH
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: LOW
      dtype: numeric
      attr: feature
      action: normalization
  - column:
      name: TOPEN
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: LCLOSE
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: CHG
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: PCHG
      dtype: string
      attr: [label, feature]
      action: normalization
  - column:
      name: TURNOVER
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: VOTURNOVER
      dtype: string
      attr: [feature]
      action: normalization
  - column:
      name: VATURNOVER
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: TCAP
      dtype: numeric
      attr: [feature]
      action: normalization
  - column:
      name: MCAP
      dtype: numeric
      attr: [feature]
      action: normalization