MA:
  time_period1: 5
  time_period2: 10
  time_period3: 20

BBI:
  time_period1: 3
  time_period2: 6
  time_period3: 12
  time_period4: 24

BIAS:
  time_period1: 6
  time_period2: 12
  time_period3: 24

BRAR:
  time_period: 26

DMA:
  time_period1: 10
  time_period2: 50
  time_period3: 10

MTM:
  time_period1: 12
  time_period2: 6

PSY:
  time_period1: 6
  time_period2: 12

VR:
  time_period: 24

KDJ:
  time_period1: 9
  time_period2: 3
  time_period3: 3

MACD:
  time_period1: 9
  time_period2: 12
  time_period3: 26

BOLL:
  time_period: 20
  nbdev_up: 2
  nbdev_down: 2

CCI:
  time_period: 14

ROC:
  time_period1: 12
  time_period2: 6

RSI:
  time_period1: 6
  time_period2: 12
  time_period3: 24

WR:
  time_period1: 6
  time_period2: 14