import random

DEFAULT_LAST_UPDATE_DATE = '1991-01-01'

MONEY_163_URL = "http://quotes.money.163.com"
QUOTES_MONEY_163_URL = "http://quotes.money.163.com/service/chddata.html?"

FINANCE_SINA_URL = "https://vip.stock.finance.sina.com.cn/quotes_service/api/json_v2.php"
FINANCE_SINA_MONEY_FLOW = "MoneyFlow.ssl_qsfx_lscjfb"


class CompanyInfoXPath:
    type = "//div[@class='col_l_01']/table[@class='table_bg001 border_box limit_sale table_details']/tr[1]/td[2]/text()"
    region = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[1]/td[4]/text()"
    short_name = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[2]/td[2]/text()"
    address = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[2]/td[4]/text()"
    full_name = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[3]/td[2]/text()"
    telephone = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[3]/td[4]/text()"
    english_name = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[4]/td[2]/text()"
    email = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[4]/td[4]/text()"
    capital = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[5]/td[2]/text()"
    chairman = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[5]/td[4]/text()"
    main_business = "//table[@class='table_bg001 border_box limit_sale table_details']/tr[10]/td[2]/text()"
    industry = "//div[@class='inner_box industry_info']/span[1]/em/a/text()"


COMPANY_INFO_XPATH = {
    "type": "//div[@class='col_l_01']/table[@class='table_bg001 border_box limit_sale table_details']/tr[1]/td[2]/text()",
    "region": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[1]/td[4]/text()",
    "short_name": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[2]/td[2]/text()",
    "address": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[2]/td[4]/text()",
    "full_name": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[3]/td[2]/text()",
    "telephone": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[3]/td[4]/text()",
    "english_name": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[4]/td[2]/text()",
    "email": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[4]/td[4]/text()",
    "capital": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[5]/td[2]/text()",
    "chairman": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[5]/td[4]/text()",
    "main_business": "//table[@class='table_bg001 border_box limit_sale table_details']/tr[10]/td[2]/text()",
    "industry": "//div[@class='inner_box industry_info']/span[1]/em/a/text()"
}

ZYCWZB_COL_MAPPING = {"CODE": "CODE",
                      "报告日期": "DATE",
                      "基本每股收益(元)": "JBMGSY_Y",
                      "每股净资产(元)": "MGJZC_Y",
                      "每股经营活动产生的现金流量净额(元)": "MGJYHDCSDXJLLJE_Y",
                      "主营业务收入(万元)": "ZYYWSR_WY",
                      "主营业务利润(万元)": "ZYYWLR_WY",
                      "营业利润(万元)": "YYLR_WY",
                      "投资收益(万元)": "TZSY_WY",
                      "营业外收支净额(万元)": "YYWSZJE_WY",
                      "利润总额(万元)": "LRZE_WY",
                      "净利润(万元)": "JLR_WY",
                      "净利润(扣除非经常性损益后)(万元)": "JLR_KCFJCXSYH_WY",
                      "经营活动产生的现金流量净额(万元)": "JYHDCSDXJLLJE_WY",
                      "现金及现金等价物净增加额(万元)": "XJJXJDJWJZJE_WY",
                      "总资产(万元)": "ZZC_WY",
                      "流动资产(万元)": "LDZC_WY",
                      "总负债(万元)": "ZFZ_WY",
                      "流动负债(万元)": "LDFZ_WY",
                      "股东权益不含少数股东权益(万元)": "GDQY_WY",
                      "净资产收益率加权(%)": "JZCSYLJQ",
                      "PERIOD_TYPE ": "PERIOD_TYPE"
                      }

YLNL_COL_MAPPING = {"CODE": "CODE",
                    "报告日期": "DATE",
                    "总资产利润率(%)": "ZZCLRL",
                    "主营业务利润率(%)": "ZYYWLRL",
                    "总资产净利润率(%)": "ZZCJLRL",
                    "成本费用利润率(%)": "CBFYLRL",
                    "营业利润率(%)": "YYLRL",
                    "主营业务成本率(%)": "ZYYWCBL",
                    "销售净利率(%)": "XSJLL",
                    "净资产收益率(%)": "JZCSYL",
                    "股本报酬率(%)": "GBBCL",
                    "净资产报酬率(%)": "JZCBCL",
                    "资产报酬率(%)": "ZCBCL",
                    "销售毛利率(%)": "XSMLL",
                    "三项费用比重(%)": "SXFYBZ",
                    "非主营比重(%)": "FZYBZ",
                    "主营利润比重(%)": "ZYLRBZ",
                    "PERIOD_TYPE": "PERIOD_TYPE"
                    }

CHNL_COL_MAPPING = {"CODE": "CODE",
                    "报告日期": "DATE",
                    "流动比率(%)": "LDBL",
                    "速动比率(%)": "SDBL",
                    "现金比率(%)": "XJBL",
                    "利息支付倍数(%)": "LXZFBS",
                    "资产负债率(%)": "ZCFZL",
                    "长期债务与营运资金比率(%)": "CQZWYYYZJBL",
                    "股东权益比率(%)": "GDQYBL",
                    "长期负债比率(%)": "CQFZBL",
                    "股东权益与固定资产比率(%)": "GDQYYGDZCBL",
                    "负债与所有者权益比率(%)": "FZYSYZQYBL",
                    "长期资产与长期资金比率(%)": "CQZCYCQZJBL",
                    "资本化比率(%)": "ZBHBL",
                    "固定资产净值率(%)": "GDZCJZL",
                    "资本固定化比率(%)": "ZBGDHBL",
                    "产权比率(%)": "CQBL",
                    "清算价值比率(%)": "QSJZBL",
                    "固定资产比重(%)": "GDZCBZ",
                    "PERIOD_TYPE": "PERIOD_TYPE"
                    }

CZNL_COL_MAPPING = {"CODE": "CODE",
                    "报告日期": "DATE",
                    "主营业务收入增长率(%)": "ZYYWSRZZL",
                    "净利润增长率(%)": "JLRZZL",
                    "净资产增长率(%)": "JZCZZL",
                    "总资产增长率(%)": "ZZCZZL",
                    "PERIOD_TYPE": "PERIOD_TYPE"
                    }

YYNL_COL_MAPPING = {"CODE": "CODE",
                    "报告日期": "DATE",
                    "应收账款周转率(次)": "YSZKZZL",
                    "应收账款周转天数(天)": "YSZKZZTS",
                    "存货周转率(次)": "CHZZL",
                    "固定资产周转率(次)": "GDZCZZL",
                    "总资产周转率(次)": "ZZCZZL",
                    "存货周转天数(天)": "CHZZTS",
                    "总资产周转天数(天)": "ZZCZZTS",
                    "流动资产周转率(次)": "LDZCZZL",
                    "流动资产周转天数(天)": "LDZCZZTS",
                    "经营现金净流量对销售收入比率(%)": "JYXJJLLDXSSRBL",
                    "资产的经营现金流量回报率(%)": "ZCDJYXJLLHBL",
                    "经营现金净流量与净利润的比率(%)": "JYXJJLLYJLRDBL",
                    "经营现金净流量对负债比率(%)": "JYXJJLLDFZBL",
                    "现金流量比率(%)": "XJLLBL",
                    "PERIOD_TYPE": "PERIOD_TYPE"
                    }

ZCFZB_COL_MAPPING = {"CODE": "CODE",
                     "报告日期": "DATE",
                     "货币资金(万元)": "HBZJ_WY",
                     "结算备付金(万元)": "JSBFJ_WY",
                     "拆出资金(万元)": "CCZJ_WY",
                     "交易性金融资产(万元)": "JYXJRZC_WY",
                     "衍生金融资产(万元)": "YSJRZC_WY",
                     "应收票据(万元)": "YSPJ_WY",
                     "应收账款(万元)": "YSZK_WY",
                     "预付款项(万元)": "YFKX_WY",
                     "应收保费(万元)": "YSBF_WY",
                     "应收分保账款(万元)": "YSFBZK_WY",
                     "应收分保合同准备金(万元)": "YSFBHTZBJ_WY",
                     "应收利息(万元)": "YSLX_WY",
                     "应收股利(万元)": "YSFX_WY",
                     "其他应收款(万元)": "QTYSK_WY",
                     "应收出口退税(万元)": "YSCKTS_WY",
                     "应收补贴款(万元)": "YSBTK_WY",
                     "应收保证金(万元)": "YSBZJ_WY",
                     "内部应收款(万元)": "NBYSK_WY",
                     "买入返售金融资产(万元)": "MRFSJRZJ_WY",
                     "存货(万元)": "CH_WY",
                     "待摊费用(万元)": "DTFY_WY",
                     "待处理流动资产损益(万元)": "DCLLDZCSY_WY",
                     "一年内到期的非流动资产(万元)": "YNNDQDFLDZC_WY",
                     "其他流动资产(万元)": "QTLDZC_WY",
                     "流动资产合计(万元)": "LDZCHJ_WY",
                     "发放贷款及垫款(万元)": "FFDKJDK_WY",
                     "可供出售金融资产(万元)": "KGCSJRZC_WY",
                     "持有至到期投资(万元)": "CYZDQZC_WY",
                     "长期应收款(万元)": "CQYSK_WY",
                     "长期股权投资(万元)": "CQGQTZ_WY",
                     "其他长期投资(万元)": "QTCQTZ_WY",
                     "投资性房地产(万元)": "TZXFDC_WY",
                     "固定资产原值(万元)": "GDZCYZ_WY",
                     "累计折旧(万元)": "LJZJ_WY",
                     "固定资产净值(万元)": "GDZCJZ_WY",
                     "固定资产减值准备(万元)": "GDZCJZZB_WY",
                     "固定资产(万元)": "GDZC_WY",
                     "在建工程(万元)": "ZJGC_WY",
                     "工程物资(万元)": "GCWZ_WY",
                     "固定资产清理(万元)": "GDZCQL_WY",
                     "生产性生物资产(万元)": "SCXSWZC_WY",
                     "公益性生物资产(万元)": "GYXSWZC_WY",
                     "油气资产(万元)": "YQZC_WY",
                     "无形资产(万元)": "WXZC_WY",
                     "开发支出(万元)": "KFZC_WY",
                     "商誉(万元)": "SY_WY",
                     "长期待摊费用(万元)": "CQDTFY_WY",
                     "股权分置流通权(万元)": "GQFZLTQ_WY",
                     "递延所得税资产(万元)": "DYSDSZC_WY",
                     "其他非流动资产(万元)": "QTFLDZC_WY",
                     "非流动资产合计(万元)": "FLDZCHJ_WY",
                     "资产总计(万元)": "ZCHJ_WY",
                     "短期借款(万元)": "DQJK_WY",
                     "向中央银行借款(万元)": "XZYYHJK_WY",
                     "吸收存款及同业存放(万元)": "XSCKJTYCF_WY",
                     "拆入资金(万元)": "CRZJ_WY",
                     "交易性金融负债(万元)": "JYXJRFZ_WY",
                     "衍生金融负债(万元)": "YSJRFZ_WY",
                     "应付票据(万元)": "YFPQ_WY",
                     "应付账款(万元)": "YFZK_WY",
                     "预收账款(万元)": "YFKZ_WY",
                     "卖出回购金融资产款(万元)": "MCHGJRZCK_WY",
                     "应付手续费及佣金(万元)": "YFSXFJYJ_WY",
                     "应付职工薪酬(万元)": "YFZGXC_WY",
                     "应交税费(万元)": "YJSF_WY",
                     "应付利息(万元)": "YFLX_WY",
                     "应付股利(万元)": "YFGX_WY",
                     "其他应交款(万元)": "QTYSJ_WY",
                     "应付保证金(万元)": "YFBZJ_WY",
                     "内部应付款(万元)": "NBYFK_WY",
                     "其他应付款(万元)": "QTYFK_WY",
                     "预提费用(万元)": "YTFY_WY",
                     "预计流动负债(万元)": "YJLDFZ_WY",
                     "应付分保账款(万元)": "YFFBZK_WY",
                     "保险合同准备金(万元)": "BXHTZBJ_WY",
                     "代理买卖证券款(万元)": "DLMMZQK_WY",
                     "代理承销证券款(万元)": "DLCXZQK_WY",
                     "国际票证结算(万元)": "GJPZJS_WY",
                     "国内票证结算(万元)": "GNPZJS_WY",
                     "递延收益(万元)": "DYSY_WY",
                     "应付短期债券(万元)": "YFDQZQ_WY",
                     "一年内到期的非流动负债(万元)": "YNNDQDFLDFZ_WY",
                     "其他流动负债(万元)": "QTLDFZ_WY",
                     "流动负债合计(万元)": "LDFZHJ_WY",
                     "长期借款(万元)": "CQJK_WY",
                     "应付债券(万元)": "YFZQ_WY",
                     "长期应付款(万元)": "CQYFK_WY",
                     "专项应付款(万元)": "ZXYFK_WY",
                     "预计非流动负债(万元)": "YJFLDFZ_WY",
                     "长期递延收益(万元)": "CQDYSY_WY",
                     "递延所得税负债(万元)": "DYSDSFZ_WY",
                     "其他非流动负债(万元)": "QTFLDFZ_WY",
                     "非流动负债合计(万元)": "FLDFZHJ_WY",
                     "负债合计(万元)": "FZHJ_WY",
                     "实收资本(或股本)(万元)": "SSZB_HGB_WY",
                     "资本公积(万元)": "ZBGJ_WY",
                     "减:库存股(万元)": "J_KCG_WY",
                     "专项储备(万元)": "ZXCB_WY",
                     "盈余公积(万元)": "YYGJ_WY",
                     "一般风险准备(万元)": "YBFXZB_WY",
                     "未确定的投资损失(万元)": "WQDDTZSS_WY",
                     "未分配利润(万元)": "WFPLR_WY",
                     "拟分配现金股利(万元)": "JFPXJGL_WY",
                     "外币报表折算差额(万元)": "WBBBZSCE_WY",
                     "归属于母公司股东权益合计(万元)": "GSYMGSGDQYHJ_WY",
                     "少数股东权益(万元)": "SSGDQY_WY",
                     "所有者权益(或股东权益)合计(万元)": "SYZQYHJ_WY",
                     "负债和所有者权益(或股东权益)总计(万元)": "FZHSYZQYHJ_WY"
                     }

LRB_COL_MAPPING = {"CODE": "CODE",
                   "报告日期": "DATE",
                   "营业总收入(万元)": "YYZSR_WY",
                   "营业收入(万元)": "YYSR_WY",
                   "利息收入(万元)": "LXSR_WY",
                   "已赚保费(万元)": "YZBF_WY",
                   "手续费及佣金收入(万元)": "SXFJYJSR_WY",
                   "房地产销售收入(万元)": "FDCXXSR_WY",
                   "其他业务收入(万元)": "QTYESR_WY",
                   "营业总成本(万元)": "YYZCB_WY",
                   "营业成本(万元)": "YYCB_WY",
                   "利息支出(万元)": "LXZC_WY",
                   "手续费及佣金支出(万元)": "SXFJYJZC_WY",
                   "房地产销售成本(万元)": "FDCXXCB_WY",
                   "研发费用(万元)": "YFFY_WY",
                   "退保金(万元)": "TBJ_WY",
                   "赔付支出净额(万元)": "PFZCJE_WY",
                   "提取保险合同准备金净额(万元)": "TQBXHTZBJJE_WY",
                   "保单红利支出(万元)": "BDHLZC_WY",
                   "分保费用(万元)": "FBFY_WY",
                   "其他业务成本(万元)": "QTCBFY_WY",
                   "营业税金及附加(万元)": "YYSJJFJ_WY",
                   "销售费用(万元)": "XSFY_WY",
                   "管理费用(万元)": "GLFY_WY",
                   "财务费用(万元)": "CWFY_WY",
                   "资产减值损失(万元)": "ZCJZSS_WY",
                   "公允价值变动收益(万元)": "GYJJBDSY_WY",
                   "投资收益(万元)": "TZSY_WY",
                   "对联营企业和合营企业的投资收益(万元)": "DLYQYHHYQYDTZSY_WY",
                   "汇兑收益(万元)": "HDSY_WY",
                   "期货损益(万元)": "QHSY_WY",
                   "托管收益(万元)": "TGSY_WY",
                   "补贴收入(万元)": "BTSR_WY",
                   "其他业务利润(万元)": "QTYWLR_WY",
                   "营业利润(万元)": "YYLR_WY",
                   "营业外收入(万元)": "YYWSR_WY",
                   "营业外支出(万元)": "YYWZC_WY",
                   "非流动资产处置损失(万元)": "FLDZCCZSS_WY",
                   "利润总额(万元)": "LRZE_WY",
                   "所得税费用(万元)": "SDSFY_WY",
                   "未确认投资损失(万元)": "WQRRZSS_WY",
                   "净利润(万元)": "JLR_WY",
                   "归属于母公司所有者的净利润(万元)": "GSYMGSSYZDJLR_WY",
                   "被合并方在合并前实现净利润(万元)": "BHBFZHBQSXJLR_WY",
                   "少数股东损益(万元)": "SSGDSY_WY",
                   "基本每股收益": "JBMGSY",
                   "稀释每股收益": "XSMGSY"
                   }

XJLLB_COL_MAPPING = {"CODE": "CODE",
                     "报告日期": "DATE",
                     "销售商品、提供劳务收到的现金(万元)": "XSSP_TGLWSDDXJ_WY",
                     "客户存款和同业存放款项净增加额(万元)": "KHCKHTYCFKXJZJE_WY",
                     "向中央银行借款净增加额(万元": "XZYYHJKJZJE_WY",
                     "向其他金融机构拆入资金净增加额(万元)": "XQTJRJGCRZJJZJE_WY",
                     "收到原保险合同保费取得的现金(万元)": "SDYBXHTBFQDDXJ_WY",
                     "收到再保险业务现金净额(万元)": "SDZBXYWXJJE_WY",
                     "保户储金及投资款净增加额(万元)": "BHCJJTZJJZJE_WY",
                     "处置交易性金融资产净增加额(万元)": "CZJJXJRZCJZJE_WY",
                     "收取利息、手续费及佣金的现金(万元)": "SQLX_SXFJYJDXJ_WY",
                     "拆入资金净增加额(万元)": "CRZJJZJE_WY",
                     "回购业务资金净增加额(万元)": "HGYWZJJEJE_WY",
                     "收到的税费返还(万元)": "SDDSFFH_WY",
                     "收到的其他与经营活动有关的现金(万元)": "SDDQTYJYHDYGDXJ_WY",
                     "经营活动现金流入小计(万元)": "JYHDXJLRXJ_WY",
                     "购买商品、接受劳务支付的现金(万元)": "GMSP_JSLWZFDXJ_WY",
                     "客户贷款及垫款净增加额(万元)": "KHDKJDKJZJE_WY",
                     "存放中央银行和同业款项净增加额(万元)": "CFZYYHHTYKXJZJE_WY",
                     "支付原保险合同赔付款项的现金(万元)": "ZFYBXHTPFKXDXJ_WY",
                     "支付利息、手续费及佣金的现金(万元)": "ZFLX_SXFJYJDXJ_WY",
                     "支付保单红利的现金(万元)": "ZFBDHLDXJ_WY",
                     "支付给职工以及为职工支付的现金(万元)": "ZFGZGYJWZGZFDXJ_WY",
                     "支付的各项税费(万元)": "ZFDGXSF_WY",
                     "支付的其他与经营活动有关的现金(万元)": "ZFDQTYJYHDYGDXJ_WY",
                     "经营活动现金流出小计(万元)": "JYHDXJLCXJ_WY",
                     "经营活动产生的现金流量净额(万元)": "JYHDCSDXJLLJE_WY",
                     "收回投资所收到的现金(万元)": "HSTZSSDDXJ_WY",
                     "取得投资收益所收到的现金(万元)": "QDTZSYSSDDXJ_WY",
                     "处置固定资产、无形资产和其他长期资产所收回的现金净额(万元)": "CZGDZC_WXZCHQTCQZCSHSDXJJE_WY",
                     "处置子公司及其他营业单位收到的现金净额(万元)": "CZZGSJQTYYDWSDDXJJE_WY",
                     "收到的其他与投资活动有关的现金(万元)": "SDDQTYTZHDYGDXJ_WY",
                     "减少质押和定期存款所收到的现金(万元)": "JSZYHDQCKSSDDXJ_WY",
                     "投资活动现金流入小计(万元)": "TZHDXJLRXJ_WY",
                     "购建固定资产、无形资产和其他长期资产所支付的现金(万元)": "GJGDZX_WXZJHQTCQZCSZFDXJ_WY",
                     "投资所支付的现金(万元)": "TZSZFDXJ_WY",
                     "质押贷款净增加额(万元)": "ZYDKJZJE_WY",
                     "取得子公司及其他营业单位支付的现金净额(万元)": "QDZGSJQTYYDWZFDXJJE_WY",
                     "支付的其他与投资活动有关的现金(万元)": "ZFDQTYTZHDYGDXJ_WY",
                     "增加质押和定期存款所支付的现金(万元)": "ZJZYHDQCKSZFDXJ_WY",
                     "投资活动现金流出小计(万元)": "TZHDXJLCXJ_WY",
                     "投资活动产生的现金流量净额(万元)": "TZHDCSDXJLLJE_WY",
                     "吸收投资收到的现金(万元)": "XSTZSDDXJ_WY",
                     "其中：子公司吸收少数股东投资收到的现金(万元)": "ZGSXSXSGDTZSDDXJ_WY",
                     "取得借款收到的现金(万元)": "QDJKSDDXJ_WY",
                     "发行债券收到的现金(万元)": "FXZQSDDXJ_WY",
                     "收到其他与筹资活动有关的现金(万元)": "SDQTYCZHDYGDXJ_WY",
                     "筹资活动现金流入小计(万元)": "CZHDXJLRXJ_WY",
                     "偿还债务支付的现金(万元)": "CHZWZFDXJ_WY",
                     "分配股利、利润或偿付利息所支付的现金(万元)": "FPGL_LRHCFLXSZFDXJ_WY",
                     "其中：子公司支付给少数股东的股利、利润(万元)": "ZGSZFSSGDDGL_LR_WY",
                     "支付其他与筹资活动有关的现金(万元)": "ZFQTYCZHDYGDXJ_WY",
                     "筹资活动现金流出小计(万元)": "CZHDXJLCXJ_WY",
                     "筹资活动产生的现金流量净额(万元)": "CZHDCSDXJLLJE_WY",
                     "汇率变动对现金及现金等价物的影响(万元)": "HLBDDXJJXJDJWDYX_WY",
                     "现金及现金等价物净增加额(万元)": "XJJXJDJWJZJE_WY",
                     "加:期初现金及现金等价物余额(万元)": "QCXJJXJDJWYE_WY",
                     "期末现金及现金等价物余额(万元)": "QMXJJXJDJWYE_WY",
                     "净利润(万元)": "JLR_WY",
                     "少数股东损益(万元)": "SSGDQY_WY",
                     "未确认的投资损失(万元)": "WQRDTZSS_WY",
                     "资产减值准备(万元)": "ZCJZZB_WY",
                     "固定资产折旧、油气资产折耗、生产性物资折旧(万元)": "GDZCZJ_YQZCZH_SCXWZZJ_WY",
                     "无形资产摊销(万元)": "WXZCTX_WY",
                     "长期待摊费用摊销(万元)": "CQDTFYTX_WY",
                     "待摊费用的减少(万元)": "DXFYDJS_WY",
                     "预提费用的增加(万元)": "YTFYDZJ_WY",
                     "处置固定资产、无形资产和其他长期资产的损失(万元)": "CZGDZC_WXZCHQTCQZCDSS_WY",
                     "固定资产报废损失(万元)": "GDZCBFSS_WY",
                     "公允价值变动损失(万元)": "GYJZBDSS_WY",
                     "递延收益增加(减：减少)(万元)": "DYSYZJ_WY",
                     "预计负债(万元)": "YJFZ_WY",
                     "财务费用(万元)": "CWFY_WY",
                     "投资损失(万元)": "TZSS_WY",
                     "递延所得税资产减少(万元)": "DYSDSZCJS_WY",
                     "递延所得税负债增加(万元)": "DYSDSFZZJ_WY",
                     "存货的减少(万元)": "CHDJS_WY",
                     "经营性应收项目的减少(万元)": "JYXYSXMDJS_WY",
                     "经营性应付项目的增加(万元)": "JYXYFXMDZJ_WY",
                     "已完工尚未结算款的减少(减:增加)(万元)": "YWGSWJSKDJS_WY",
                     "已结算尚未完工款的增加(减:减少)(万元)": "YJSSWWGKDZJ_WY",
                     "其他(万元)": "QT_WY",
                     "经营活动产生现金流量净额(万元)": "JYHDCSXJLLJE_WY",
                     "债务转为资本(万元)": "ZWZWZB_WY",
                     "一年内到期的可转换公司债券(万元)": "YNNDQDKZHGSZQ_WY",
                     "融资租入固定资产(万元)": "RZZRGDZC_WY",
                     "现金的期末余额(万元)": "XJDQMYE_WY",
                     "现金的期初余额(万元)": "XJDQCYE_WY",
                     "现金等价物的期末余额(万元)": "XJJDJWDQMYE_WY",
                     "现金等价物的期初余额(万元)": "XJJDJWDQCYE_WY",
                     "现金及现金等价物的净增加额(万元)": "XJJXJDJWDJZJE_WY"
                     }

SSE_URL = "http://query.sse.com.cn//sseQuery/commonExcelDd.do"
SSE_PARAMS = {"sqlId": "COMMON_SSE_CP_GPJCTPZ_GPLB_GP_L",
              "type": "inParams",
              "CSRC_CODE": "",
              "STOCK_CODE": "",
              "REG_PROVINCE": "",
              "STOCK_TYPE": 1,
              "COMPANY_STATUS": "2, 4, 5, 7, 8"}
SSE_HEADERS = {"Accept-Encoding": "gzip, deflate",
               "Host": "query.sse.com.cn",
               "Referer": "http://www.sse.com.cn/"}

SZSE_URL = "http://www.szse.cn/api/report/ShowReport"
SZSE_PARAMS = {"SHOWTYPE": "xlsx",
               "CATALOGID": "1110",
               "TABKEY": "tab1",
               "random": random.random()}
