CREATE VIEW `vw_stock_data_daily` AS
    SELECT
        `b`.`CODE` AS `CODE`,
        `b`.`DATE` AS `DATE`,
        `b`.`TCLOSE` AS `TCLOSE`,
        `b`.`HIGH` AS `HIGH`,
        `b`.`LOW` AS `LOW`,
        `b`.`TOPEN` AS `TOPEN`,
        `b`.`LCLOSE` AS `LCLOSE`,
        `b`.`CHG` AS `CHG`,
        `b`.`PCHG` AS `PCHG`,
        `b`.`TURNOVER` AS `TURNOVER`,
        `b`.`VOTURNOVER` AS `VOTURNOVER`,
        `b`.`VATURNOVER` AS `VATURNOVER`,
        `b`.`TCAP` AS `TCAP`,
        `b`.`MCAP` AS `MCAP`,
        `t`.`MA5` AS `MA5`,
        `t`.`MA10` AS `MA10`,
        `t`.`MA20` AS `MA20`,
        `t`.`BBI` AS `BBI`,
        `t`.`BIAS6` AS `BIAS6`,
        `t`.`BIAS12` AS `BIAS12`,
        `t`.`BIAS24` AS `BIAS24`,
        `t`.`BR` AS `BR`,
        `t`.`AR` AS `AR`,
        `t`.`DMA` AS `DMA`,
        `t`.`AMA` AS `AMA`,
        `t`.`MTM` AS `MTM`,
        `t`.`MAMTM` AS `MAMTM`,
        `t`.`PSY6` AS `PSY6`,
        `t`.`PSY12` AS `PSY12`,
        `t`.`VR` AS `VR`,
        `t`.`KDJ_K` AS `KDJ_K`,
        `t`.`KDJ_D` AS `KDJ_D`,
        `t`.`KDJ_J` AS `KDJ_J`,
        `t`.`MACD_DIF` AS `MACD_DIF`,
        `t`.`MACD_DEA` AS `MACD_DEA`,
        `t`.`MACD` AS `MACD`,
        `t`.`BOLL_UPPER` AS `BOLL_UPPER`,
        `t`.`BOLL_MIDDLE` AS `BOLL_MIDDLE`,
        `t`.`BOLL_LOWER` AS `BOLL_LOWER`,
        `t`.`CCI` AS `CCI`,
        `t`.`ROC` AS `ROC`,
        `t`.`MAROC` AS `MAROC`,
        `t`.`RSI6` AS `RSI6`,
        `t`.`RSI12` AS `RSI12`,
        `t`.`RSI24` AS `RSI24`,
        `t`.`WR6` AS `WR6`,
        `t`.`WR14` AS `WR14`
    FROM
        (`tb_stock_basic_daily` `b`
        JOIN `tb_stock_tech_daily` `t`)
    WHERE
        ((`t`.`CODE` = `b`.`CODE`)
            AND (`t`.`DATE` = `b`.`DATE`));
