CREATE TABLE `tb_stock_basic_daily` (
  `CODE` varchar(10) NOT NULL,
  `DATE` date NOT NULL,
  `TCLOSE` float DEFAULT NULL,
  `HIGH` float DEFAULT NULL,
  `LOW` float DEFAULT NULL,
  `TOPEN` float DEFAULT NULL,
  `LCLOSE` float DEFAULT NULL,
  `CHG` float DEFAULT NULL,
  `PCHG` float DEFAULT NULL,
  `TURNOVER` float DEFAULT NULL,
  `VOTURNOVER` float DEFAULT NULL,
  `VATURNOVER` float DEFAULT NULL,
  `TCAP` float DEFAULT NULL,
  `MCAP` float DEFAULT NULL,
  PRIMARY KEY (`CODE`,`DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `tb_stock_list` (
  `CODE` varchar(10) NOT NULL,
  `NAME` varchar(100) DEFAULT NULL,
  `LAST_UPDATE_DATE` date DEFAULT NULL,
  `ADDRESS` varchar(500) DEFAULT NULL,
  `INDUSTRY` varchar(50) DEFAULT NULL,
  `FIRST_DATE_TO_MARKET` date DEFAULT NULL,
  `TOTAL_SHARE` int(20) DEFAULT NULL,
  `SHARE_IN_MARKET` int(20) DEFAULT NULL,
  PRIMARY KEY (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
