# -*- coding: UTF-8 -*-
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, String, Date, Integer, Float

Base = declarative_base()


class TBStockInfo(Base):
    __tablename__ = 'tb_stock_info'

    code = Column(String, name="CODE", primary_key=True)
    name = Column(String, name="NAME")
    last_update_date = Column(Date, name="LAST_UPDATE_DATE")
    address = Column(String, name="ADDRESS")
    industry = Column(String, name="INDUSTRY")
    first_date_to_market = Column(Date, name="FIRST_DATE_TO_MARKET")
    total_share = Column(Integer, name="TOTAL_SHARE")
    share_in_market = Column(Integer, name="SHARE_IN_MARKET")
    type = Column(String, name="TYPE")
    region = Column(String, name="REGION")
    short_name = Column(String, name="SHORT_NAME")
    full_name = Column(String, name="FULL_NAME")
    english_name = Column(String, name="ENGLISH_NAME")
    email = Column(String, name="EMAIL")
    telephone = Column(String, name="TELEPHONE")
    capital = Column(String, name="CAPITAL")
    chairman = Column(String, name="CHAIRMAN")
    main_business = Column(String, name="MAIN_BUSINESS")

    def __repr__(self):
        return "<Stock(CODE='%s', NAME='%s', LASTUPDATEDATE='%s')>" % \
               (self.code, self.name, self.last_update_date)


class TBDailyBasicData(Base):
    __tablename__ = "tb_stock_basic_daily"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    t_close = Column(Float, name="TCLOSE")
    high = Column(Float, name="HIGH")
    low = Column(Float, name="LOW")
    t_open = Column(Float, name="TOPEN")
    l_close = Column(Float, name="LCLOSE")
    chg = Column(Float, name="CHG")
    p_chg = Column(Float, name="PCHG")
    turnover = Column(Float, name="TURNOVER")
    vo_turnover = Column(Float, name="VOTURNOVER")
    va_turnover = Column(Float, name="VATURNOVER")
    t_cap = Column(Float, name="TCAP")
    m_cap = Column(Float, name="MCAP")

    def __repr__(self):
        return "<Stock Basic Daily(CODE='%s', DATE='%s')>" % (self.code, self.date)


class TBDailyTechData(Base):
    __tablename__ = "tb_stock_tech_daily"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    ma5 = Column(Float, name="MA5")
    ma10 = Column(Float, name="MA10")
    ma20 = Column(Float, name="MA20")
    bbi = Column(Float, name="BBI")
    bias6 = Column(Float, name="BIAS6")
    bias12 = Column(Float, name="BIAS12")
    bias24 = Column(Float, name="BIAS24")
    br = Column(Float, name="BR")
    ar = Column(Float, name="AR")
    dma = Column(Float, name="DMA")
    ama = Column(Float, name="AMA")
    mtm = Column(Float, name="MTM")
    mamtm = Column(Float, name="MAMTM")
    psy6 = Column(Float, name="PSY6")
    psy12 = Column(Float, name="PSY12")
    vr = Column(Float, name="VR")
    kdj_k = Column(Float, name="KDJ_K")
    kdj_d = Column(Float, name="KDJ_D")
    kdj_j = Column(Float, name="KDJ_J")
    macd_dif = Column(Float, name="MACD_DIF")
    macd_dea = Column(Float, name="MACD_DEA")
    macd = Column(Float, name="MACD")
    boll_upper = Column(Float, name="BOLL_UPPER")
    boll_middle = Column(Float, name="BOLL_MIDDLE")
    boll_lower = Column(Float, name="BOLL_LOWER")
    cci = Column(Float, name="CCI")
    roc = Column(Float, name="ROC")
    maroc = Column(Float, name="MAROC")
    rsi6 = Column(Float, name="RSI6")
    rsi12 = Column(Float, name="RSI12")
    rsi24 = Column(Float, name="RSI24")
    wr6 = Column(Float, name="WR6")
    wr14 = Column(Float, name="WR14")

    def __repr__(self):
        return "<Stock Tech Daily(CODE='%s', DATE='%s')>" % (self.code, self.date)


class TBFinancialZYCWZB(Base):
    __tablename__ = "tb_stock_financial_zycwzb"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    jbmgsy_y = Column(Float, name="JBMGSY_Y")
    mgjzc_y = Column(Float, name="MGJZC_Y")
    mgjyhdcsdxjllje_y = Column(Float, name="MGJYHDCSDXJLLJE_Y")
    zyywsr_wy = Column(Float, name="ZYYWSR_WY")
    zyywlr_wy = Column(Float, name="ZYYWLR_WY")
    yylr_wy = Column(Float, name="YYLR_WY")
    tzsy_wy = Column(Float, name="TZSY_WY")
    yywszje_wy = Column(Float, name="YYWSZJE_WY")
    lrze_wy = Column(Float, name="LRZE_WY")
    jlr_wy = Column(Float, name="JLR_WY")
    jrr_kcfjcxsyh_wy = Column(Float, name="JLR_KCFJCXSYH_WY")
    jyhdcsdxjllje_wy = Column(Float, name="JYHDCSDXJLLJE_WY")
    xjjxjdjwjzje_wy = Column(Float, name="XJJXJDJWJZJE_WY")
    zzc_wy = Column(Float, name="ZZC_WY")
    ldzc_wy = Column(Float, name="LDZC_WY")
    zfz_wy = Column(Float, name="ZFZ_WY")
    ldfz_wy = Column(Float, name="LDFZ_WY")
    dgqy_wy = Column(Float, name="GDQY_WY")
    zjcsyljq = Column(Float, name="JZCSYLJQ")


class TBFinancialYYNL(Base):
    __tablename__ = "tb_stock_financial_yynl"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    yszkzzl = Column(Float, name="YSZKZZL")
    yszkzts = Column(Float, name="YSZKZZTS")
    chzzl = Column(Float, name="CHZZL")
    gdzczzl = Column(Float, name="GDZCZZL")
    zzczzl = Column(Float, name="ZZCZZL")
    chzzts = Column(Float, name="CHZZTS")
    zzczzts = Column(Float, name="ZZCZZTS")
    ldzczzl = Column(Float, name="LDZCZZL")
    ldzczzts = Column(Float, name="LDZCZZTS")
    jyxjjlldxssrbl = Column(Float, name="JYXJJLLDXSSRBL")
    zcdjyxjllhbl = Column(Float, name="ZCDJYXJLLHBL")
    jyxjjllyjlrdbl = Column(Float, name="JYXJJLLYJLRDBL")
    jyxjjlldfzbl = Column(Float, name="JYXJJLLDFZBL")
    xjllbl = Column(Float, name="XJLLBL")


class TBFinancialYLNL(Base):
    __tablename__ = "tb_stock_financial_ylnl"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    zzclrl = Column(Float, name="ZZCLRL")
    zyywlrl = Column(Float, name="ZYYWLRL")
    zzcjlrl = Column(Float, name="ZZCJLRL")
    cbfylrl = Column(Float, name="CBFYLRL")
    yylrl = Column(Float, name="YYLRL")
    zyywcbl = Column(Float, name="ZYYWCBL")
    xsjll = Column(Float, name="XSJLL")
    jzcsyl = Column(Float, name="JZCSYL")
    gbbcl = Column(Float, name="GBBCL")
    jzcbcl = Column(Float, name="JZCBCL")
    zcbcl = Column(Float, name="ZCBCL")
    xsmll = Column(Float, name="XSMLL")
    sxfybz = Column(Float, name="SXFYBZ")
    fzybz = Column(Float, name="FZYBZ")
    zylrbz = Column(Float, name="ZYLRBZ")


class TBFinancialCZNL(Base):
    __tablename__ = "tb_stock_financial_cznl"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    zyywsrzzl = Column(Float, name="ZYYWSRZZL")
    jlrzzl = Column(Float, name="JLRZZL")
    jzczzl = Column(Float, name="JZCZZL")
    zzczzl = Column(Float, name="ZZCZZL")


class TBFinancialCHNL(Base):
    __tablename__ = "tb_stock_financial_chnl"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    ldbl = Column(Float, name="LDBL")
    sdbl = Column(Float, name="SDBL")
    xjbl = Column(Float, name="XJBL")
    lxzfbs = Column(Float, name="LXZFBS")
    zcfzl = Column(Float, name="ZCFZL")
    cqzwyyyzjbl = Column(Float, name="CQZWYYYZJBL")
    gdqybl = Column(Float, name="GDQYBL")
    cqfzbl = Column(Float, name="CQFZBL")
    gdqyygdzcbl = Column(Float, name="GDQYYGDZCBL")
    fzysyzqybl = Column(Float, name="FZYSYZQYBL")
    cqzcycqzjbl = Column(Float, name="CQZCYCQZJBL")
    zbhbl = Column(Float, name="ZBHBL")
    gdzcjzl = Column(Float, name="GDZCJZL")
    zbgdhbl = Column(Float, name="ZBGDHBL")
    cqbl = Column(Float, name="CQBL")
    qsjzbl = Column(Float, name="QSJZBL")
    gdzcbz = Column(Float, name="GDZCBZ")


class TBFinancialZCFZB(Base):
    __tablename__ = "tb_stock_financial_zcfzb"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    hbzj_wy = Column(Float, name="HBZJ_WY")
    jsbfj_wy = Column(Float, name="JSBFJ_WY")
    cczj_wy = Column(Float, name="CCZJ_WY")
    jyxjrzc_wy = Column(Float, name="JYXJRZC_WY")
    ysjrzc_wy = Column(Float, name="YSJRZC_WY")
    yspj_wy = Column(Float, name="YSPJ_WY")
    yszk_wy = Column(Float, name="YSZK_WY")
    yfkx_wy = Column(Float, name="YFKX_WY")
    ysbf_wy = Column(Float, name="YSBF_WY")
    ysfbzk_wy = Column(Float, name="YSFBZK_WY")
    ysfbhtzbj_wy = Column(Float, name="YSFBHTZBJ_WY")
    yslx_wy = Column(Float, name="YSLX_WY")
    ysfx_wy = Column(Float, name="YSFX_WY")
    qtysk_wy = Column(Float, name="QTYSK_WY")
    ysckts_wy = Column(Float, name="YSCKTS_WY")
    ysbtk_wy = Column(Float, name="YSBTK_WY")
    ysbzj_wy = Column(Float, name="YSBZJ_WY")
    nbysk_wy = Column(Float, name="NBYSK_WY")
    mrfsjrzj_wy = Column(Float, name="MRFSJRZJ_WY")
    ch_wy = Column(Float, name="CH_WY")
    dtfy_wy = Column(Float, name="DTFY_WY")
    dclldzcsy_wy = Column(Float, name="DCLLDZCSY_WY")
    ynndqdfldzc_wy = Column(Float, name="YNNDQDFLDZC_WY")
    qtldzc_wy = Column(Float, name="QTLDZC_WY")
    ldzchj_wy = Column(Float, name="LDZCHJ_WY")
    ffdkjdk_wy = Column(Float, name="FFDKJDK_WY")
    kgcsjrzc_wy = Column(Float, name="KGCSJRZC_WY")
    cyzdqzc_wy = Column(Float, name="CYZDQZC_WY")
    cqysk_wy = Column(Float, name="CQYSK_WY")
    cqgqtz_wy = Column(Float, name="CQGQTZ_WY")
    qtcqtz_wy = Column(Float, name="QTCQTZ_WY")
    tzxfdc_wy = Column(Float, name="TZXFDC_WY")
    gdzcyz_wy = Column(Float, name="GDZCYZ_WY")
    ljzj_wy = Column(Float, name="LJZJ_WY")
    gdzcjz_wy = Column(Float, name="GDZCJZ_WY")
    gdzcjzzb_wy = Column(Float, name="GDZCJZZB_WY")
    gdzc_wy = Column(Float, name="GDZC_WY")
    zjgc_wy = Column(Float, name="ZJGC_WY")
    gcwz_wy = Column(Float, name="GCWZ_WY")
    gdzcql_wy = Column(Float, name="GDZCQL_WY")
    scxswzc_wy = Column(Float, name="SCXSWZC_WY")
    gyxswzc_wy = Column(Float, name="GYXSWZC_WY")
    yqzc_wy = Column(Float, name="YQZC_WY")
    wxzc_wy = Column(Float, name="WXZC_WY")
    kfzc_wy = Column(Float, name="KFZC_WY")
    sy_wy = Column(Float, name="SY_WY")
    cqdtfy_wy = Column(Float, name="CQDTFY_WY")
    gqfzltq_wy = Column(Float, name="GQFZLTQ_WY")
    dysdszc_wy = Column(Float, name="DYSDSZC_WY")
    qtfldzc_wy = Column(Float, name="QTFLDZC_WY")
    fldzchj_wy = Column(Float, name="FLDZCHJ_WY")
    zchj_wy = Column(Float, name="ZCHJ_WY")
    dqjk_wy = Column(Float, name="DQJK_WY")
    xzyyhjk_wy = Column(Float, name="XZYYHJK_WY")
    xsckjtycf_wy = Column(Float, name="XSCKJTYCF_WY")
    crzj_wy = Column(Float, name="CRZJ_WY")
    jyxjrfz_wy = Column(Float, name="JYXJRFZ_WY")
    ysjrfz_wy = Column(Float, name="YSJRFZ_WY")
    yfpq_wy = Column(Float, name="YFPQ_WY")
    yfzk_wy = Column(Float, name="YFZK_WY")
    yfkz_wy = Column(Float, name="YFKZ_WY")
    mchgjrzck_wy = Column(Float, name="MCHGJRZCK_WY")
    yfsxfjyj_wy = Column(Float, name="YFSXFJYJ_WY")
    yfzgxc_wy = Column(Float, name="YFZGXC_WY")
    yjsf_wy = Column(Float, name="YJSF_WY")
    yflx_wy = Column(Float, name="YFLX_WY")
    yfgx_wy = Column(Float, name="YFGX_WY")
    qtysj_wy = Column(Float, name="QTYSJ_WY")
    yfbzj_wy = Column(Float, name="YFBZJ_WY")
    nbyfk_wy = Column(Float, name="NBYFK_WY")
    qtyfk_wy = Column(Float, name="QTYFK_WY")
    ytfy_wy = Column(Float, name="YTFY_WY")
    yjldfz_wy = Column(Float, name="YJLDFZ_WY")
    yffbzk_wy = Column(Float, name="YFFBZK_WY")
    bxhtzbj_wy = Column(Float, name="BXHTZBJ_WY")
    dlmmzqk_wy = Column(Float, name="DLMMZQK_WY")
    dlcxzqk_wy = Column(Float, name="DLCXZQK_WY")
    gjpzjs_wy = Column(Float, name="GJPZJS_WY")
    gnpzjs_wy = Column(Float, name="GNPZJS_WY")
    dysy_wy = Column(Float, name="DYSY_WY")
    yfdqzq_wy = Column(Float, name="YFDQZQ_WY")
    ynndqdfldfz_wy = Column(Float, name="YNNDQDFLDFZ_WY")
    qtldfz_wy = Column(Float, name="QTLDFZ_WY")
    ldfzhj_wy = Column(Float, name="LDFZHJ_WY")
    cqjk_wy = Column(Float, name="CQJK_WY")
    yfzq_wy = Column(Float, name="YFZQ_WY")
    cqyfk_wy = Column(Float, name="CQYFK_WY")
    zxyfk_wy = Column(Float, name="ZXYFK_WY")
    yjfldfz_wy = Column(Float, name="YJFLDFZ_WY")
    cqdysy_wy = Column(Float, name="CQDYSY_WY")
    dysdsfz_wy = Column(Float, name="DYSDSFZ_WY")
    qtfldfz_wy = Column(Float, name="QTFLDFZ_WY")
    fldfzhj_wy = Column(Float, name="FLDFZHJ_WY")
    fzhj_wy = Column(Float, name="FZHJ_WY")
    sszb_hgb_wy = Column(Float, name="SSZB_HGB_WY")
    zbgj_wy = Column(Float, name="ZBGJ_WY")
    j_kcg_wy = Column(Float, name="J_KCG_WY")
    zxcb_wy = Column(Float, name="ZXCB_WY")
    yygj_wy = Column(Float, name="YYGJ_WY")
    ybfxzb_wy = Column(Float, name="YBFXZB_WY")
    wqddtzss_wy = Column(Float, name="WQDDTZSS_WY")
    wfplr_wy = Column(Float, name="WFPLR_WY")
    jfpxjgl_wy = Column(Float, name="JFPXJGL_WY")
    wbbbzsce_wy = Column(Float, name="WBBBZSCE_WY")
    gsymgsgdqyhj_wy = Column(Float, name="GSYMGSGDQYHJ_WY")
    ssgdqy_wy = Column(Float, name="SSGDQY_WY")
    syzqyhj_wy = Column(Float, name="SYZQYHJ_WY")
    fzhsyzqyhj_wy = Column(Float, name="FZHSYZQYHJ_WY")


class TBFinancialLRB(Base):
    __tablename__ = "tb_stock_financial_lrb"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    yyzsr_wy = Column(Float, name="YYZSR_WY")
    yysr_wy = Column(Float, name="YYSR_WY")
    lxsr_wy = Column(Float, name="LXSR_WY")
    yzbf_wy = Column(Float, name="YZBF_WY")
    sxfjyjsr_wy = Column(Float, name="SXFJYJSR_WY")
    fdcxxsr_wy = Column(Float, name="FDCXXSR_WY")
    qtyesr_wy = Column(Float, name="QTYESR_WY")
    yyzcb_wy = Column(Float, name="YYZCB_WY")
    yycb_wy = Column(Float, name="YYCB_WY")
    lxzc_wy = Column(Float, name="LXZC_WY")
    sxfjyjzc_wy = Column(Float, name="SXFJYJZC_WY")
    fdcxxcb_wy = Column(Float, name="FDCXXCB_WY")
    yffy_wy = Column(Float, name="YFFY_WY")
    tbj_wy = Column(Float, name="TBJ_WY")
    pfzcje_wy = Column(Float, name="PFZCJE_WY")
    tqbxhtzbjje_wy = Column(Float, name="TQBXHTZBJJE_WY")
    bdhlzc_wy = Column(Float, name="BDHLZC_WY")
    fbfy_wy = Column(Float, name="FBFY_WY")
    qtcbfy_wy = Column(Float, name="QTCBFY_WY")
    yysjjfj_wy = Column(Float, name="YYSJJFJ_WY")
    xsfy_wy = Column(Float, name="XSFY_WY")
    glfy_wy = Column(Float, name="GLFY_WY")
    cwfy_wy = Column(Float, name="CWFY_WY")
    zcjzss_wy = Column(Float, name="ZCJZSS_WY")
    gyjjbdsy_wy = Column(Float, name="GYJJBDSY_WY")
    tzsy_wy = Column(Float, name="TZSY_WY")
    dlyqyhhyqydtzsy_wy = Column(Float, name="DLYQYHHYQYDTZSY_WY")
    hdsy_wy = Column(Float, name="HDSY_WY")
    qhsy_wy = Column(Float, name="QHSY_WY")
    tgsy_wy = Column(Float, name="TGSY_WY")
    btsr_wy = Column(Float, name="BTSR_WY")
    qtywlr_wy = Column(Float, name="QTYWLR_WY")
    yylr_wy = Column(Float, name="YYLR_WY")
    yywsr_wy = Column(Float, name="YYWSR_WY")
    yywzc_wy = Column(Float, name="YYWZC_WY")
    fldzcczss_wy = Column(Float, name="FLDZCCZSS_WY")
    lrze_wy = Column(Float, name="LRZE_WY")
    sdsfy_wy = Column(Float, name="SDSFY_WY")
    wqrrzss_wy = Column(Float, name="WQRRZSS_WY")
    jlr_wy = Column(Float, name="JLR_WY")
    gsymgssyzdjlr_wy = Column(Float, name="GSYMGSSYZDJLR_WY")
    bhbfzhbqsxjlr_wy = Column(Float, name="BHBFZHBQSXJLR_WY")
    ssgdsy_wy = Column(Float, name="SSGDSY_WY")
    jbmgsy = Column(Float, name="JBMGSY")
    xsmgsy = Column(Float, name="XSMGSY")


class TBFinancialXJLLB(Base):
    __tablename__ = "tb_stock_financial_xjllb"

    code = Column(String, name="CODE", primary_key=True)
    date = Column(Date, name="DATE", primary_key=True)
    period_type = Column(String, name="PERIOD_TYPE", primary_key=True)
    xssp_tglwsddxj_wy = Column(Float, name="XSSP_TGLWSDDXJ_WY")
    khckhtycfkxjzje_wy = Column(Float, name="KHCKHTYCFKXJZJE_WY")
    xzyyhjkjzje_wy = Column(Float, name="XZYYHJKJZJE_WY")
    xqtjrjgcrzjjzje_wy = Column(Float, name="XQTJRJGCRZJJZJE_WY")
    sdybxhtbfqddxj_wy = Column(Float, name="SDYBXHTBFQDDXJ_WY")
    sdzbxywxjje_wy = Column(Float, name="SDZBXYWXJJE_WY")
    bhcjjtzjjzje_wy = Column(Float, name="BHCJJTZJJZJE_WY")
    czjjxjrzcjzje_wy = Column(Float, name="CZJJXJRZCJZJE_WY")
    sqlx_sxfjyjdxj_wy = Column(Float, name="SQLX_SXFJYJDXJ_WY")
    crzjjzje_wy = Column(Float, name="CRZJJZJE_WY")
    hgywzjjeje_wy = Column(Float, name="HGYWZJJEJE_WY")
    sddsffh_wy = Column(Float, name="SDDSFFH_WY")
    sddqtyjyhdygdxj_wy = Column(Float, name="SDDQTYJYHDYGDXJ_WY")
    jyhdxjlrxj_wy = Column(Float, name="JYHDXJLRXJ_WY")
    gmsp_jslwzfdxj_wy = Column(Float, name="GMSP_JSLWZFDXJ_WY")
    khdkjdkjzje_wy = Column(Float, name="KHDKJDKJZJE_WY")
    cfzyyhhtykxjzje_wy = Column(Float, name="CFZYYHHTYKXJZJE_WY")
    zfybxhtpfkxdxj_wy = Column(Float, name="ZFYBXHTPFKXDXJ_WY")
    zflx_sxfjyjdxj_wy = Column(Float, name="ZFLX_SXFJYJDXJ_WY")
    zfbdhldxj_wy = Column(Float, name="ZFBDHLDXJ_WY")
    zfgzgyjwzgzfdxj_wy = Column(Float, name="ZFGZGYJWZGZFDXJ_WY")
    zfdgxsf_wy = Column(Float, name="ZFDGXSF_WY")
    zfdqtyjyhdygdxj_wy = Column(Float, name="ZFDQTYJYHDYGDXJ_WY")
    jyhdxjlcxj_wy = Column(Float, name="JYHDXJLCXJ_WY")
    jyhdcsdxjllje_wy = Column(Float, name="JYHDCSDXJLLJE_WY")
    hstzssddxj_wy = Column(Float, name="HSTZSSDDXJ_WY")
    qdtzsyssddxj_wy = Column(Float, name="QDTZSYSSDDXJ_WY")
    czgdzc_wxzchqtcqzcshsdxjje_wy = Column(Float, name="CZGDZC_WXZCHQTCQZCSHSDXJJE_WY")
    czzgsjqtyydwsddxjje_wy = Column(Float, name="CZZGSJQTYYDWSDDXJJE_WY")
    sddqtytzhdygdxj_wy = Column(Float, name="SDDQTYTZHDYGDXJ_WY")
    jszyhdqckssddxj_wy = Column(Float, name="JSZYHDQCKSSDDXJ_WY")
    tzhdxjlrxj_wy = Column(Float, name="TZHDXJLRXJ_WY")
    gjgdzx_wxzjhqtcqzcszfdxj_wy = Column(Float, name="GJGDZX_WXZJHQTCQZCSZFDXJ_WY")
    tzszfdxj_wy = Column(Float, name="TZSZFDXJ_WY")
    zydkjzje_wy = Column(Float, name="ZYDKJZJE_WY")
    qdzgsjqtyydwzfdxjje_wy = Column(Float, name="QDZGSJQTYYDWZFDXJJE_WY")
    zfdqtytzhdygdxj_wy = Column(Float, name="ZFDQTYTZHDYGDXJ_WY")
    zjzyhdqckszfdxj_wy = Column(Float, name="ZJZYHDQCKSZFDXJ_WY")
    tzhdxjlcxj_wy = Column(Float, name="TZHDXJLCXJ_WY")
    tzhdcsdxjllje_wy = Column(Float, name="TZHDCSDXJLLJE_WY")
    xstzsddxj_wy = Column(Float, name="XSTZSDDXJ_WY")
    zgsxsxsgdtzsddxj_wy = Column(Float, name="ZGSXSXSGDTZSDDXJ_WY")
    qdjksddxj_wy = Column(Float, name="QDJKSDDXJ_WY")
    fxzqsddxj_wy = Column(Float, name="FXZQSDDXJ_WY")
    sdqtyczhdygdxj_wy = Column(Float, name="SDQTYCZHDYGDXJ_WY")
    czhdxjlrxj_wy = Column(Float, name="CZHDXJLRXJ_WY")
    chzwzfdxj_wy = Column(Float, name="CHZWZFDXJ_WY")
    fpgl_lrhcflxszfdxj_wy = Column(Float, name="FPGL_LRHCFLXSZFDXJ_WY")
    zgszfssgddgl_lr_wy = Column(Float, name="ZGSZFSSGDDGL_LR_WY")
    zfqtyczhdygdxj_wy = Column(Float, name="ZFQTYCZHDYGDXJ_WY")
    czhdxjlcxj_wy = Column(Float, name="CZHDXJLCXJ_WY")
    czhdcsdxjllje_wy = Column(Float, name="CZHDCSDXJLLJE_WY")
    hlbddxjjxjdjwdyx_wy = Column(Float, name="HLBDDXJJXJDJWDYX_WY")
    xjjxjdjwjzje_wy = Column(Float, name="XJJXJDJWJZJE_WY")
    qcxjjxjdjwye_wy = Column(Float, name="QCXJJXJDJWYE_WY")
    qmxjjxjdjwye_wy = Column(Float, name="QMXJJXJDJWYE_WY")
    jlr_wy = Column(Float, name="JLR_WY")
    ssgdqy_wy = Column(Float, name="SSGDQY_WY")
    wqrdtzss_wy = Column(Float, name="WQRDTZSS_WY")
    zcjzzb_wy = Column(Float, name="ZCJZZB_WY")
    gdzczj_yqzczh_scxwzzj_wy = Column(Float, name="GDZCZJ_YQZCZH_SCXWZZJ_WY")
    wxzctx_wy = Column(Float, name="WXZCTX_WY")
    cqdtfytx_wy = Column(Float, name="CQDTFYTX_WY")
    dxfydjs_wy = Column(Float, name="DXFYDJS_WY")
    ytfydzj_wy = Column(Float, name="YTFYDZJ_WY")
    czgdzc_wxzchqtcqzcdss_wy = Column(Float, name="CZGDZC_WXZCHQTCQZCDSS_WY")
    gdzcbfss_wy = Column(Float, name="GDZCBFSS_WY")
    gyjzbdss_wy = Column(Float, name="GYJZBDSS_WY")
    dysyzj_wy = Column(Float, name="DYSYZJ_WY")
    yjfz_wy = Column(Float, name="YJFZ_WY")
    cwfy_wy = Column(Float, name="CWFY_WY")
    tzss_wy = Column(Float, name="TZSS_WY")
    dysdszcjs_wy = Column(Float, name="DYSDSZCJS_WY")
    dysdsfzzj_wy = Column(Float, name="DYSDSFZZJ_WY")
    chdjs_wy = Column(Float, name="CHDJS_WY")
    jyxysxmdjs_wy = Column(Float, name="JYXYSXMDJS_WY")
    jyxyfxmdzj_wy = Column(Float, name="JYXYFXMDZJ_WY")
    ywgswjskdjs_wy = Column(Float, name="YWGSWJSKDJS_WY")
    yjsswwgkdzj_wy = Column(Float, name="YJSSWWGKDZJ_WY")
    qt_wy = Column(Float, name="QT_WY")
    jyhdcsxjllje_wy = Column(Float, name="JYHDCSXJLLJE_WY")
    zwzwzb_wy = Column(Float, name="ZWZWZB_WY")
    ynndqdkzhgszq_wy = Column(Float, name="YNNDQDKZHGSZQ_WY")
    rzzrgdzc_wy = Column(Float, name="RZZRGDZC_WY")
    xjdqmye_wy = Column(Float, name="XJDQMYE_WY")
    xjdqcye_wy = Column(Float, name="XJDQCYE_WY")
    xjjdjwdqmye_wy = Column(Float, name="XJJDJWDQMYE_WY")
    xjjdjwdqcye_wy = Column(Float, name="XJJDJWDQCYE_WY")
    xjjxjdjwdjzje_wy = Column(Float, name="XJJXJDJWDJZJE_WY")

